version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - dashboard

  frontend:
    image: your-frontend-image:latest
    container_name: frontend-container
    # add other configurations as needed

  dashboard:
    image: your-dashboard-image:latest
    container_name: dashboard-container
    # add other configurations as needed
