version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - optimumai-frontend
      - optimumai-dashboard

  optimumai-frontend:
    image: frontend-image:latest
    container_name: frontend-container
    # add other configurations as needed

  optimumai-dashboard:
    image: dashboard-image:latest
    container_name: dashboard-container
    # add other configurations as needed
